image: docker:latest
services:
  - name: docker:dind
variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package

maven-build:
  image: maven:3.6-openjdk-15
  stage: build
  script: "mvn package -B"
  artifacts:
    name: "$CI_PROJECT_NAME" 
    paths:
      - target/

docker-build-main:
  image: docker:stable
  stage: package
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - main
    
docker-build:
  image: docker:stable
  # Official docker image.
  stage: package
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - main